version: '3.8'

services:
  ai-chat:
    container_name: ai-chat
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - OPENAI_API_KEY=sk-proj-...
